version: "3.8"
services:
    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5439:5432"
        volumes:
            - postgresql-volume:/var/lib/postgresql/data

    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - DB_SOURCE=postgresql://postgres:postgres@host.docker.internal:5439/postgres?sslmode=disable
        depends_on:
            - postgres
        entrypoint: ["/app/start.sh"]
        command: ["/app/main"]

volumes:
    postgresql-volume:
